spring:
  application:
    name: macrostruct-api

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: NON_NULL

  output:
    ansi:
      enabled: ALWAYS

jwt:
  expires: 86400
  public-key: classpath:keys/public.pub
  private-key: classpath:keys/private.key
